name: CD (local to s3)

on:
  push:
    branches: [ "updated_files" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      S3_BUCKET: pawspal-frontend-prod
 

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

     #upload local files to s3
      - name: Upload APK to S3 folder
        run: |
          aws s3 rm "s3://${S3_BUCKET}/updated_files/ --recursive
          aws s3 cp . "s3://${S3_BUCKET}/updated_files/ --recursive
